title: Geoff Chan
description: Personal website of Geoffrey Chan
url: https://geoffchan23.github.io
baseurl: ""

# Build settings
markdown: kramdown
permalink: pretty
collections:
  art:
    output: true
    permalink: /art/:title/

exclude:
  - docs/

defaults:
  - scope:
      path: ""
      type: art
    values:
      layout: art
