title: Geoff Chan
description: Personal website of Geoffrey Chan
url: https://geoffchan23.github.io
baseurl: ""

# Build settings
markdown: kramdown
permalink: pretty
collections:
  comics:
    output: true
    permalink: /comics/:title/

defaults:
  - scope:
      path: ""
      type: comics
    values:
      layout: comic