const CACHE = 'uu-d358f93342';
const PRECACHE = ["./","app.MU3UBNJC.css","app.Y6ASSDI7.js","art/alluring-narwhal.webp","art/americorn.webp","art/annoying-flying-unicorn.webp","art/baby-narwhal.webp","art/baby-unicorn-black.webp","art/baby-unicorn-blue.webp","art/baby-unicorn-brown.webp","art/baby-unicorn-death.webp","art/baby-unicorn-green.webp","art/baby-unicorn-orange.webp","art/baby-unicorn-pink.webp","art/baby-unicorn-purple.webp","art/baby-unicorn-rainbow.webp","art/baby-unicorn-red.webp","art/baby-unicorn-white.webp","art/baby-unicorn-yellow.webp","art/back-kick.webp","art/barbed-wire.webp","art/basic-unicorn-blue.webp","art/basic-unicorn-green.webp","art/basic-unicorn-indigo.webp","art/basic-unicorn-orange.webp","art/basic-unicorn-purple.webp","art/basic-unicorn-red.webp","art/basic-unicorn-yellow.webp","art/black-knight-unicorn.webp","art/blatant-thievery.webp","art/blinding-light.webp","art/broken-stable.webp","art/caffeine-overload.webp","art/card-back.webp","art/chainsaw-unicorn.webp","art/change-of-luck.webp","art/classy-narwhal.webp","art/claw-machine.webp","art/dark-angel-unicorn.webp","art/double-dutch.webp","art/extremely-destructive-unicorn.webp","art/ginormous-unicorn.webp","art/glitter-bomb.webp","art/glitter-tornado.webp","art/good-deal.webp","art/greedy-flying-unicorn.webp","art/kiss-of-life.webp","art/llamacorn.webp","art/magical-flying-unicorn.webp","art/magical-kittencorn.webp","art/majestic-flying-unicorn.webp","art/mermaid-unicorn.webp","art/mother-goose-unicorn.webp","art/mystical-vortex.webp","art/nanny-cam.webp","art/narwhal-torpedo.webp","art/narwhal.webp","art/necromancer-unicorn.webp","art/neigh.webp","art/pandamonium.webp","art/queen-bee-unicorn.webp","art/rainbow-aura.webp","art/rainbow-lasso.webp","art/rainbow-unicorn.webp","art/re-target.webp","art/reset-button.webp","art/rhinocorn.webp","art/sadistic-ritual.webp","art/seductive-unicorn.webp","art/shabby-the-narwhal.webp","art/shake-up.webp","art/shark-with-a-horn.webp","art/slowdown.webp","art/stabby-the-unicorn.webp","art/stable-artillery.webp","art/super-neigh.webp","art/swift-flying-unicorn.webp","art/targeted-destruction.webp","art/the-great-narwhal.webp","art/tiny-stable.webp","art/two-for-one.webp","art/unfair-bargain.webp","art/unicorn-on-the-cob.webp","art/unicorn-phoenix.webp","art/unicorn-poison.webp","art/unicorn-swap.webp","art/yay.webp","icons/apple-touch-icon.png","icons/icon-192.png","icons/icon-512.png","icons/icon-maskable-512.png","manifest.webmanifest"];
self.addEventListener('install', (e) => { e.waitUntil(caches.open(CACHE).then((c) => c.addAll(PRECACHE))); });
self.addEventListener('activate', (e) => { e.waitUntil(caches.keys().then((ks) => Promise.all(ks.filter((k) => k !== CACHE && k !== 'uu-fonts').map((k) => caches.delete(k)))).then(() => self.clients.claim())); });
self.addEventListener('message', (e) => { if (e.data === 'SKIP_WAITING') self.skipWaiting(); });
self.addEventListener('fetch', (e) => {
  const req = e.request; if (req.method !== 'GET') return;
  const url = new URL(req.url);
  const isShell = url.origin === location.origin && (url.pathname.endsWith('/') || url.pathname.endsWith('/index.html') || url.pathname.endsWith('manifest.webmanifest'));
  const isFont = url.hostname.endsWith('gstatic.com') || url.hostname.endsWith('googleapis.com');
  if (isShell) { e.respondWith(fetch(req).then((r) => { const copy = r.clone(); caches.open(CACHE).then((c) => c.put(req, copy)); return r; }).catch(() => caches.match(req, { ignoreSearch: true }).then((r) => r || caches.match('./')))); return; }
  if (isFont) { e.respondWith(caches.open('uu-fonts').then(async (c) => { const hit = await c.match(req); if (hit) return hit; const r = await fetch(req); if (r.ok) c.put(req, r.clone()); return r; }).catch(() => fetch(req))); return; }
  e.respondWith(caches.match(req, { ignoreSearch: true }).then((r) => r || fetch(req)));
});
